- core/core-api/src/main/kotlin/io/raemian/core/auth/config/WebSecurityConfig.kt
- core/core-api/src/main/kotlin/io/raemian/core/auth/service/OAuth2UserService.kt
> chore(#1):  코드 정리

- core/core-api/src/main/kotlin/io/raemian/core/auth/config/CorsConfig.kt
- core/core-api/src/main/kotlin/io/raemian/core/auth/config/WebSecurityConfig.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/token/RefreshToken.kt
> feat(#1): edit response token

- application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- application/api/src/main/kotlin/io/raemian/api/auth/domain/CurrentUser.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- application/api/src/main/kotlin/io/raemian/api/config/JwtSecurityConfig.kt
- application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- application/api/src/main/kotlin/io/raemian/api/support/TokenProvider.kt
- application/api/src/main/resources/application.yml
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/BaseEntity.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/ExampleEntity.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/enums/OAuthProvider.kt
- storage/db-core/src/test/kotlin/io/raemian/storage/db/core/ExampleRepositoryIT.kt
#1  #16 
- 유저 닉네임, 생일 받는 api 추가 
- 유저 엔티티 수정
아직 엔티티도 없고 러프하게 짜고있는 느낌이 들어
코드는 임시로 작성해두었습니다~~
entity 추가중에 base entity 를 상속받아
id, createdAt, updatedAt 3개의 필드를 사용하는 부분이 있는데요
id 는 각자의 entity에서 사용하는게 활용도가 더 높을거 같아서 우선 빼두었는데요
의견 부탁드립니다 😀
---
> 유저 정보 수정 api 추가

- application/api/src/main/kotlin/io/raemian/api/sticker/StickerService.kt
- application/api/src/main/kotlin/io/raemian/api/sticker/controller/StickerController.kt
- application/api/src/main/kotlin/io/raemian/api/sticker/controller/response/StickerResponse.kt
- application/api/src/main/kotlin/io/raemian/api/tag/TagService.kt
- application/api/src/main/kotlin/io/raemian/api/tag/controller/TagController.kt
- application/api/src/main/kotlin/io/raemian/api/tag/controller/response/TagResponse.kt
- application/api/src/test/kotlin/io/raemian/api/CoreApiApplicationTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/sticker/StickerServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/tag/TagServiceTest.kt
- application/api/src/test/resources/application-security.yml
- application/api/src/test/resources/application.yml
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/sticker/StickerImage.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/sticker/StickerRepository.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/tag/TagRepository.kt
Goal API 작성중 (https://github.com/depromeet/amazing3-be/issues/27) Sticker와 Tag를 조회할 필요가 있어 관련 로직들을 작성합니다.
PR 내용은 금방 다시 작성하겠습니다. 진행 상황 궁금하실 것 같아 미리 올려둡니다.
> [Feature] Sticker, Tag API 작성 (#29)

- application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- application/api/src/main/kotlin/io/raemian/api/support/TokenProvider.kt
> feat(#50): edit current user info api

- application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- application/api/src/main/kotlin/io/raemian/api/goal/controller/GoalController.kt
- application/api/src/main/kotlin/io/raemian/api/sticker/controller/StickerController.kt
- application/api/src/main/kotlin/io/raemian/api/support/response/ApiResponse.kt
- application/api/src/main/kotlin/io/raemian/api/tag/controller/TagController.kt
- application/api/src/main/kotlin/io/raemian/api/task/controller/TaskController.kt
공통 Response로 Wrapping하여, 클라이언트 분들이 보다 쉽게 성공-실패 응답 여부를 확인할 수 있도록 했습니다.
위와 같은 공통 응답을 성공-실패시 Type으로 구분해 받습니다.
> [Feature] 공통 Response Wrapping (#53)

- .github/workflows/ci-cd.yml
- Github Action 기반 CI/CD 파이프라인 구축 
- Github Action 작업 과정
- jdk setup -> gradle build -> docker image build -> push to dockerhub -> deploy to server
---
> [Feature] Github Action 기반 CI/CD 파이프라인 구축 (#4)

- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalReadServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/task/TaskServiceTest.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> 유저 프로필 이미지 추가

- application/api/src/main/kotlin/io/raemian/api/config/SpringdocConfig.kt
- application/api/src/main/resources/application.yml
- application/api/src/test/resources/application.yml
- swagger 서버 url 값 환경 변수로 빼기 (#65)
- swagger 서버 url 값 환경 변수로 빼기
- api
---
> [Refactor] swagger 서버 url 값 환경 변수로 빼기(#65)

- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- application/api/src/main/resources/application-security.yml
- application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalReadServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/task/TaskServiceTest.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/UserRepository.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/enums/OAuthProvider.kt
> 네이버 로그인 추가

- application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- application/api/src/main/resources/application-security.yml
> chore: add tempcode

- application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> chore(#70): edit redirect

- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
> chore(#70): edit fe redirect url

- application/api/src/main/resources/application-security.yml
> feat(#70): edit kakao , naver client id secret url

- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalReadServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalServiceTest.kt
- application/api/src/test/kotlin/io/raemian/api/integration/task/TaskServiceTest.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/UserRepository.kt
> feat(#70): provider id 삭제

- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
> chore(#70): edit kakao

- application/api/src/main/resources/application.yml
> chore(#70): add dev profile server port 8888

- application/api/src/main/resources/application.yml
> feat(#70): delete server port

- application/api/src/main/resources/application-security.yml
- application/api/src/main/resources/application.yml
- infra/logging/src/main/resources/logback/logback-dev.xml
> feat(#70): 포트 명시적으로 작성 ,  로깅레벨 수정

- infra/logging/src/main/resources/logback/logback-dev.xml
> chore: edit dev-api log leve info -> debug

- .github/workflows/live-api-ci-cd.yml
> chore: cicid master -> main

- application/api/src/main/kotlin/io/raemian/api/config/JasyptConfig.kt
- application/api/src/main/resources/application-security.yml
- application/api/src/test/kotlin/io/raemian/api/support/JasyptTest.kt
- build.gradle.kts
- storage/db-core/src/main/resources/application-db-core.yml
> feat(#94): add encrypt

- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/domain/UserDTO.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- storage/db-core/src/main/resources/application-db-core.yml
> feat(#99): add dto, edit open-in-view

- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- storage/db-core/src/main/resources/application-db-core.yml
> feat(#99): edit osiv, add transactional

- application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> feat(#107): edit /my response

- application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- application/api/src/main/kotlin/io/raemian/api/auth/controller/response/UserResponse.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> merge develop to main

- backend/application/api/src/main/resources/application-security-live.yml
> chore: edit live kakako oauth2 enc

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/UserController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/response/UserResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/service/UserService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/service/UserService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/UserRepository.kt
> 유저네임 수정시 중복체크 추가

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/AuthController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/AuthService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/UserController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/response/UserResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/service/UserService.kt
- backend/application/api/src/main/resources/application-security-live.yml
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/UserRepository.kt
> merge develop. to main

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/UserController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/service/UserService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> feat(#132): 유저 정보수정 api 분기

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/UserController.kt
> chore(#132): lint

- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/DefaultProfileService.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/DefaultProfileController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/CreateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/UpdateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/response/DefaultProfileResponse.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/sticker/StickerService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/ProfileService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/ProfileController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/response/DefaultProfileResponse.kt
- backend/application/api/src/main/resources/application-security-local.yml
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfile.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfileRepository.kt
- backend/storage/image/src/main/kotlin/io/raemian/image/repository/ImageRepository.kt
- backend/storage/image/src/main/resources/application-image.yml
- [Feature] Default Profile 기능 추가 #138
- api에 Default Profile 전체 조회 기능 추가
- admin api에 Default Profile CRUD 기능 추가
- api
- admin
- storage/image
---
> [Feature] Default Profile 기능 추가 (api, admin api)

- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/DefaultProfileService.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/DefaultProfileController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/CreateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/UpdateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/response/DefaultProfileResponse.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/sticker/StickerService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/ProfileService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/ProfileController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/response/DefaultProfileResponse.kt
- backend/application/api/src/main/resources/application-security-local.yml
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfile.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfileRepository.kt
- backend/storage/image/src/main/kotlin/io/raemian/image/repository/ImageRepository.kt
- backend/storage/image/src/main/resources/application-image.yml
- [Feature] Default Profile 기능 추가 #138
- api에 Default Profile 전체 조회 기능 추가
- admin api에 Default Profile CRUD 기능 추가
- api
- admin
- storage/image
---
> Merge To Main

- admin-ui/src/client/default-profile.ts
- admin-ui/src/components/layout/main-menu.tsx
- admin-ui/src/components/page/default-profile/default-profile-form.tsx
- admin-ui/src/components/page/default-profile/default-profile-list.tsx
- admin-ui/src/pages/default-profile/edit/[id].tsx
- admin-ui/src/pages/default-profile/list.tsx
- admin-ui/src/pages/default-profile/new.tsx
- admin-ui/src/pages/sticker/edit/[id].tsx
- admin-ui/src/pages/sticker/list.tsx
- admin-ui/src/pages/sticker/new.tsx
- admin-ui/src/pages/tag/edit/[id].tsx
- admin-ui/src/pages/tag/list.tsx
- admin-ui/src/pages/tag/new.tsx
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/DefaultProfileService.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/DefaultProfileController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/CreateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/request/UpdateDefaultProfileRequest.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/profile/controller/response/DefaultProfileResponse.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/sticker/StickerService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/ProfileService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/ProfileController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/profile/controller/response/DefaultProfileResponse.kt
- backend/application/api/src/main/resources/application-security-local.yml
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfile.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/profile/DefaultProfileRepository.kt
- backend/storage/image/src/main/kotlin/io/raemian/image/repository/ImageRepository.kt
- backend/storage/image/src/main/resources/application-image.yml
- [Feature] Default Profile 기능 추가 #138
- admin ui에 Default Profile CRUD 기능 추가
- admin-ui
---
> [Feature] Default Profile 기능 추가 (admin-ui)

- backend/application/api/src/main/resources/application-security-dev.yml
- backend/application/api/src/main/resources/application-security-live.yml
- backend/application/api/src/main/resources/application-security-local.yml
- backend/application/api/src/main/resources/application-security-test.yml
> feat: edit kakao ouath info

- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/log/LogService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/log/UserLoginLogService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/log/LogLoginLog.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/log/UserLoginLogRepository.kt
- #150
- 로그인 시 로그 INSERT 로직 추가 (ASYNC)
- api
---
> [🌎 Feature] X: 최근 로그인 시점 / Y: 사용자 수 Admin 그래프 통계 추가 (1)

- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/LifeMapService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/LifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/OpenLifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/LifeMapDTO.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/LifeMapResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/controller/response/UserResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/domain/UserSubset.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/lifemap/LifeMapCount.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/lifemap/LifeMapCountRepository.kt
> feat(#148): add life-map view count

- backend/application/api/src/main/kotlin/io/raemian/api/goal/GoalService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/controller/GoalController.kt
- backend/application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalServiceTest.kt
Goal 조회시 자신의 Goal이 아닌 경우에만 Public 여부를 검사한다.
- Goal 조회시 자신의 Goal인 경우 Public 검사 제외 코드 추가
- 관련 테스트 코드 추가
> [🌎 Feature] Goal 조회시 자신의 Goal인 경우 Public 검사 제외 코드 추가

- backend/application/api/build.gradle.kts
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/CheeringLimiter.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/CheeringServcie.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/controller/CheeringController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/controller/request/CheeringRequest.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/controller/request/CheeringSquadPagingRequest.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/controller/response/CheererResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/controller/response/CheeringCountResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/event/CheeringEvent.kt
- backend/application/api/src/main/kotlin/io/raemian/api/cheer/event/CheeringEventHandler.kt
- backend/application/api/src/main/kotlin/io/raemian/api/config/EventConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/LifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/OpenLifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/LifeMapResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/error/ErrorInfo.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/response/ApiResponse.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/response/PageResult.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/cheer/Cheerer.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/cheer/CheererRepository.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/cheer/Cheering.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/cheer/CheeringRepository.kt
- backend/storage/db-core/src/main/resources/application-db-core-dev.yml
- backend/storage/db-core/src/main/resources/application-db-core-live.yml
- backend/storage/db-core/src/main/resources/application-db-core-local.yml
- backend/storage/db-core/src/main/resources/application-db-core-test.yml
- #149 
- 1 응원받은 수 조회 API
- 2 응원하기 API
- 3. 응원자 List 조회 API
- 4. LifeMap CountResponse에 응원하기 Count 추가
- api
---
> [🌎 Feature] 응원하기 기능 #149

- backend/application/admin/build.gradle.kts
- backend/application/admin/src/main/kotlin/io/raemian/admin/config/SchedulerConfig.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/dashboard/controller/DashboardController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/scheduler/DashboardScheduler.kt
- backend/application/admin/src/main/resources/application.yml
- backend/application/admin/src/test/resources/application.yml
- backend/infra/logging/src/main/kotlin/io/raemian/infra/logging/enums/LogTemplate.kt
- backend/infra/logging/src/main/kotlin/io/raemian/infra/logging/logger/SlackLogger.kt
- backend/infra/logging/src/main/resources/application-logging.yml
- #164 
- Admin 하루 통계치 Slack 공유 Scheduler
- infra/logging
- admin
---
> [🌎 Feature] Admin 하루 통계치 Slack 공유 Scheduler 

- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/LifeMapDTO.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/domain/UserSubset.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/lifemap/LifeMap.kt
> feat(#171): 유저 정보 추가

- backend/application/api/src/main/kotlin/io/raemian/api/goal/GoalService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/controller/GoalController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/controller/response/GoalResponse.kt
- backend/application/api/src/test/kotlin/io/raemian/api/integration/goal/GoalServiceTest.kt
> merge main to develop

- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
> feat(#171): 유저 디폴트맵 추가

- admin-ui/src/client/life-map.ts
- admin-ui/src/client/user.ts
- admin-ui/src/components/layout/default-layout.tsx
- admin-ui/src/components/layout/main-menu.tsx
- admin-ui/src/components/page/index/dashboard-statistics.tsx
- admin-ui/src/components/page/user/user-list.tsx
- admin-ui/src/pages/popup/life-map/[id].tsx
- admin-ui/src/pages/user/list.tsx
- backend/application/admin/src/main/kotlin/io/raemian/admin/lifemap/LifeMapService.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/lifemap/controller/LifeMapController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/lifemap/controller/response/GoalResponse.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/lifemap/controller/response/LifeMapResponse.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/user/UserService.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/user/controller/UserController.kt
- backend/application/admin/src/main/kotlin/io/raemian/admin/user/controller/response/UserResponse.kt
- backend/application/admin/src/main/resources/application.yml
- #163
- 유저 및 인생 지도 Admin 조회 API 작업
- 유저 및 인생 지도 Admin 조회 UI 작업
- admin-ui
- admin
---
> [🌎 Feature] Admin 회원 전체 보기 페이지 #163

- backend/application/api/src/main/kotlin/io/raemian/api/goal/domain/GoalSubset.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/LifeMapDTO.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/domain/UserSubset.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/goal/GoalRepository.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/goal/model/GoalExploreQueryResult.kt
> feat(#171): 피드에 누락된 필드 추가

- backend/application/api/Dockerfile
> chore(#187): dele indet

- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/goal/GoalRepository.kt
> feat(#171): 피드에 세부목표 삭제

- backend/application/api/build.gradle.kts
- backend/application/api/src/main/kotlin/io/raemian/api/auth/converter/AppleLoginProps.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/converter/TokenRequestEntityConverter.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/domain/UserInfoDto.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/config/PropsConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- backend/application/api/src/main/resources/application-security-dev.yml
- backend/application/api/src/main/resources/application-security-live.yml
- backend/application/api/src/main/resources/application-security-local.yml
- backend/application/api/src/main/resources/application-security-test.yml
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/enums/OAuthProvider.kt
> [🌎 Feature] 애플 아이디 로그인 추가

- backend/application/api/src/main/kotlin/io/raemian/api/auth/converter/TokenRequestEntityConverter.kt
- backend/application/api/src/main/kotlin/io/raemian/api/auth/service/OAuth2UserService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> feat(#198): edit nickname

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
> refact(#185): edit validate username

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- backend/application/api/src/main/resources/application-security-live.yml
> main <- develop

- backend/application/api/src/main/resources/application-security-dev.yml
> feat: add forward headers

- backend/application/api/src/main/resources/application-security-live.yml
> feat: add header

- backend/application/api/src/main/kotlin/io/raemian/api/auth/controller/request/UpdateUserRequest.kt
- backend/application/api/src/main/kotlin/io/raemian/api/user/service/UserService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/user/User.kt
> [Refactor] birth 관련 유저 정보 업데이트 API에 birth를 nullable로 변경

- backend/application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/CookieUtils.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/HttpCookieOAuth2AuthorizationRequestRepository.kt
- #209 
- AuthorizationRequestRepository 구현체 생성
- Session(JSESSIONID) 방식 -> Custom Cookie 방식으로 변경
- Cookie 생성용 Utils 
- https://velog.io/@smc2315/authorization-request-not-found 참고
- api
---
> [🆘 Bug] authorization_request_not_found 오류

- backend/application/api/src/main/kotlin/io/raemian/api/emoji/controller/EmojiController.kt
Emoji API Restful하게 변경
1. 엔드포인트 Restful 하게 개선
2. 불필요한 RequestBody 제거
> [🛠️ Refactor] Emoji API Restful하게 변경

- backend/application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/emoji/EmojiService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/emoji/domain/EmojiCountSubset.kt
- backend/application/api/src/main/kotlin/io/raemian/api/event/CountEventHandler.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/GoalService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/controller/GoalController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/domain/GoalExploreDTO.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/emoji/EmojiCount.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/emoji/EmojiCountRepository.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/emoji/ReactedEmojiRepository.kt
#171 
피드에 이모지 수, 내가 눌렀는지 추가
---
> 피드에 이모지 추가

- backend/application/api/src/main/kotlin/io/raemian/api/config/WebSecurityConfig.kt
- backend/application/api/src/main/kotlin/io/raemian/api/event/RunnerLock.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/constant/WebSecurityConstant.kt
- #222
- RunnerLock 필드 변수명 변경
- 대기하는 Thread 수를 의미하기 때문에 waitingThread -> watingThreadCount
- Security Uri 상수화
- 수가 점점 늘어나서 상수 클래스로 관리하려 합니다
-  H2 웹 콘솔용 WebSecurityCustomizer 제거
- local에서 dev환경 db를 바라보게 하여 H2 웹 콘솔을 더이상 사용할 일이 없어 configureH2ConsoleEnable bean 제거
`위 변경 사항은 모두 제안드리는 내용으로 다른 방식을 선호하신다면 편하게 말씀 부탁드립니다!`
- api
---
> [🛠️ Refactor] RunnerLock 필드 변수명 변경 + Security Uri 상수화 + H2 웹 콘솔용 WebSecurityCustomizer 제거

- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/domain/GoalDto.kt
> [🌎 Feature] lifemap 응답 필드 수정 #232

- backend/application/api/src/main/kotlin/io/raemian/api/event/handler/CountEventHandler.kt
- backend/application/api/src/main/kotlin/io/raemian/api/event/model/DeletedGoalEvent.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/service/GoalQueryService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/service/GoalService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/LifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/controller/OpenLifeMapController.kt
- backend/application/api/src/main/kotlin/io/raemian/api/lifemap/service/LifeMapCountQueryService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/support/response/OffsetPaginationResult.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/lifemap/LifeMapCount.kt
- #247 
- 타임라인 API 목표가 아무것도 없는 경우 Early Return (오류 수정)
- 유저 정보 기반 타임라인 조회 API 개발
- application/api
---
> [🆘 Bug] 타임라인 관련 버그 수정

- backend/application/api/src/main/kotlin/io/raemian/api/goal/model/GoalExploreCountSubset.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/service/GoalService.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/goal/GoalRepository.kt
- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/goal/model/GoalExploreQueryResult.kt
> /goal/explore 댓글 수 수정

- backend/storage/db-core/src/main/kotlin/io/raemian/storage/db/core/comment/CommentJdbcQueryRepository.kt
- #254 
- 타임라인 조회 API 내 코멘트 개수 조회 쿼리 오류 수정
- application/api
---
> [🆘 Bug] 타임라인 조회 API 내 코멘트 개수 조회 쿼리 오류 수정

- backend/application/api/src/main/kotlin/io/raemian/api/comment/service/CommentService.kt
- backend/application/api/src/main/kotlin/io/raemian/api/goal/service/GoalService.kt
#171 
목표 생성시 이벤트로 기본 카운트 늘리는 방식에서
디비 직접 질의로 변경
---
> 목표 추가시 기본 카운트 추가
